# Site settings
title: Ethan Zane Miller
email: ethanzanemiller@gmail.com
description: > 
  a programer and historian interested in the intersection of technology, ideas, and schoarship.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ethanzanemiller.com" # the base hostname & protocol for your site
twitter_username: ezmiller
github_username:  ezmiller

# Build settings
markdown: kramdown
